version: 0.2

phases:
  install:
    runtime-version:
      python: 3.9
    commands:
      python -m pip install aws-cdk-lib
      pip install -r requirements.txt
  build:
    commands:
      - echo deploymenz started
      - cdk synth
      - cdk deploy --require-approval never
  post_build:
    commands:
      - echo deployment complete
