version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt
  build:
    commands:
      - echo deployment started
      - cdk synth
      - cdk deploy GateWayStepFunction --require-approval never
  post_build:
    commands:
      - echo deployment complete
